services:
  book_api:
    container_name: "book_api"
    build:
      context: .
      dockerfile: Dockerfile
    image: book_api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./books.db:/book_api/books.db
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    container_name: "book_api_redis"
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  sqlite_data: