services:
  book_api:
    container_name: "book_api_devcontainer"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/book_api
    entrypoint: /bin/sh -c 'tail --follow /dev/null'
    volumes:
      - ..:/workspaces/book_api
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:7.4-alpine
    container_name: "redis_devcontainer"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
